# Generated by Django 3.1 on 2020-09-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='クラス名')),
                ('teachar', models.CharField(max_length=50, verbose_name='担任')),
                ('sub_teachar', models.CharField(max_length=50, verbose_name='副担任')),
                ('detail', models.CharField(max_length=200, verbose_name='学級紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='クラブ名')),
                ('advisor', models.CharField(max_length=50, verbose_name='顧問')),
                ('detail', models.CharField(max_length=200, verbose_name='クラブ紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='委員会名')),
                ('advisor', models.CharField(max_length=50, verbose_name='顧問')),
                ('detail', models.CharField(max_length=200, verbose_name='委員会説明')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='斑数')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生名')),
                ('age', models.CharField(max_length=200, verbose_name='性格')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.clubs')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.committees')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.groups')),
            ],
        ),
    ]
