# Generated by Django 3.1 on 2020-09-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='クラスコード')),
                ('grade', models.IntegerField(verbose_name='学年')),
                ('class_number', models.IntegerField(verbose_name='組')),
                ('name', models.CharField(max_length=50, verbose_name='クラス名')),
                ('detail', models.CharField(max_length=200, verbose_name='学級紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='クラブコード')),
                ('name', models.CharField(max_length=50, verbose_name='クラブ名')),
                ('detail', models.CharField(max_length=200, verbose_name='クラブ紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Committees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='委員会コード')),
                ('name', models.CharField(max_length=50, verbose_name='委員会名')),
                ('detail', models.CharField(max_length=200, verbose_name='委員会説明')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='学生コード')),
                ('name', models.CharField(max_length=50, verbose_name='学生名')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (10, 'その他')], null=True, verbose_name='性別')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('personality', models.CharField(max_length=200, verbose_name='生徒紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Teachars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='教師コード')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('position', models.CharField(max_length=50, verbose_name='担当教科')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (10, 'その他')], null=True, verbose_name='性別')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('personality', models.CharField(max_length=200, verbose_name='先生紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
            ],
        ),
        migrations.CreateModel(
            name='TeacharPodiitons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_type', models.IntegerField(blank=True, choices=[(1, '担任'), (2, '副担任'), (10, 'その他')], null=True, verbose_name='担任・副担任')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.classes', verbose_name='担当クラス')),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.clubs', verbose_name='クラブ顧問')),
                ('committees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.committees', verbose_name='委員会顧問')),
                ('teachar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_podiitons', to='promotion.teachars', verbose_name='教師')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.years', verbose_name='年度')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPodiitons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='グループ（1班,2班）')),
                ('number', models.IntegerField(verbose_name='クラス番号')),
                ('clubs_type', models.IntegerField(blank=True, choices=[(1, '一般'), (2, '部長'), (3, '副部長'), (4, 'マネージャー'), (10, 'その他')], null=True, verbose_name='クラブ役職')),
                ('committees_type', models.IntegerField(blank=True, choices=[(1, '一般'), (2, '委員長'), (3, '副委員長'), (4, '会計'), (5, '初期'), (10, 'その他')], null=True, verbose_name='委員会役職')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.classes', verbose_name='所属クラス')),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.clubs', verbose_name='クラブ活動')),
                ('committees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.committees', verbose_name='委員会')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_podiitons', to='promotion.students', verbose_name='生徒')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.years', verbose_name='年度')),
            ],
        ),
    ]
